// Code generated by go generates; DO NOT EDIT !!.
package toolprovider

import (
	_ "github.com/odit-bit/jagatai/agent/toolprovider/openmeteo"
	_ "github.com/odit-bit/jagatai/agent/toolprovider/openstreetmap"
	_ "github.com/odit-bit/jagatai/agent/toolprovider/xtime"
)
