server:
  address: "127.0.0.1:11823" #default server address listening to
  debug: false

provider: # OpenAI api compatible backend
  name: "ollama"
  model: "qwen3:1.7b" #Default
  key: ""

#
# tools:
#   - name: "openmeteo"
#     endpoint: "https://api.open-meteo.com"
#     api_key: ""
#   - name: "clock"
#     endpoint: ""
#     api_key: ""
#   - name: "osm"
